CREATE TABLE IF NOT EXISTS ha_workspace_file (
    owner_key VARCHAR(191) NOT NULL,
    agent_key VARCHAR(128) NOT NULL,
    scope_key VARCHAR(160) NOT NULL,
    workspace_area VARCHAR(32) NOT NULL DEFAULT 'USER',
    file_kind VARCHAR(32) NOT NULL DEFAULT 'DOCUMENT',
    write_policy VARCHAR(32) NOT NULL DEFAULT 'AGENT',
    path_hash CHAR(64) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    content_ref VARCHAR(1024) NOT NULL,
    media_type VARCHAR(255) NOT NULL DEFAULT 'text/plain; charset=utf-8',
    checksum_sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (owner_key, agent_key, scope_key, path_hash)
);

CREATE TABLE IF NOT EXISTS ha_workspace_operation (
    owner_key VARCHAR(191) NOT NULL,
    agent_key VARCHAR(128) NOT NULL,
    scope_key VARCHAR(160) NOT NULL,
    path_hash CHAR(64) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    operation_id VARCHAR(191) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'AGENT',
    audit_sequence BIGINT NOT NULL AUTO_INCREMENT,
    actor_id VARCHAR(191),
    before_version BIGINT,
    after_version BIGINT,
    before_ref VARCHAR(1024),
    after_ref VARCHAR(1024),
    before_checksum CHAR(64),
    after_checksum CHAR(64),
    before_size BIGINT,
    after_size BIGINT,
    media_type VARCHAR(255) NOT NULL DEFAULT 'text/plain; charset=utf-8',
    session_id VARCHAR(191),
    turn_id VARCHAR(191),
    tool_call_id VARCHAR(191),
    change_json LONGTEXT NOT NULL,
    applied_version BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (owner_key, agent_key, scope_key, path_hash, operation_id),
    KEY idx_ha_workspace_operation_time (owner_key, agent_key, created_at),
    UNIQUE KEY uk_ha_workspace_audit_sequence (audit_sequence),
    KEY idx_ha_workspace_audit_file (owner_key,agent_key,scope_key,path_hash,audit_sequence),
    KEY idx_ha_workspace_audit_scope (owner_key,agent_key,scope_key,audit_sequence)
);
