CREATE TABLE IF NOT EXISTS ha_conversation_history (
    history_sequence BIGINT NOT NULL AUTO_INCREMENT,
    owner_key VARCHAR(191) NOT NULL,
    session_id VARCHAR(191) NOT NULL,
    turn_id VARCHAR(191) NOT NULL,
    record_type VARCHAR(32) NOT NULL,
    record_id VARCHAR(191) NOT NULL,
    message_sequence BIGINT,
    artifact_id VARCHAR(191),
    artifact_role VARCHAR(32),
    payload_json LONGTEXT NOT NULL,
    timeline_sequence BIGINT,
    timeline_payload_json LONGTEXT,
    timeline_created_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (history_sequence),
    UNIQUE KEY uk_ha_history_record (owner_key, record_type, record_id),
    UNIQUE KEY uk_ha_history_message (owner_key, session_id, message_sequence),
    KEY idx_ha_history_session (owner_key, session_id, history_sequence),
    KEY idx_ha_history_timeline (owner_key, session_id, timeline_sequence),
    KEY idx_ha_history_turn (owner_key, turn_id, record_type),
    KEY idx_ha_history_artifact (owner_key, artifact_id, created_at),
    KEY idx_ha_history_artifact_session (owner_key, session_id, record_type, artifact_role, created_at)
);
